# Generated by Django 3.2.7 on 2021-10-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='clienteCorreo',
            field=models.EmailField(db_column='email', default='rkg@mascotitas.com', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='clientePassword',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='productoDescripcion',
            field=models.CharField(db_column='descripcion', default='none', max_length=100, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='productoEstado',
            field=models.BooleanField(db_column='estado', default=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='productoNombre',
            field=models.CharField(db_column='nombre', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='productoPrecio',
            field=models.DecimalField(db_column='precio', decimal_places=2, max_digits=5, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='productoUnidadMedida',
            field=models.TextField(choices=[('UN', 'UNIDAD')], db_column='unidad_medida', default='UN', verbose_name='UnidadMedida'),
        ),
    ]
