# Generated by Django 3.2.7 on 2021-10-06 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcionmodel',
            name='clientes',
        ),
        migrations.AddField(
            model_name='adopcionmodel',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteAdopcion', to='gestion.clientemodel'),
        ),
    ]
