# Generated by Django 3.2.7 on 2021-10-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidomodel',
            name='detalleSubTotal',
            field=models.DecimalField(db_column='sub_total', decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='pedidoTotal',
            field=models.DecimalField(db_column='total', decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='productoPrecio',
            field=models.DecimalField(db_column='precio', decimal_places=2, max_digits=9, verbose_name='precio'),
        ),
    ]
