# Generated by Django 3.2.7 on 2021-10-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_clientemodel_clientedocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteDocumento',
            field=models.CharField(db_column='documento', max_length=9),
        ),
    ]
