# Generated by Django 3.2.7 on 2021-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_adopcionmodel_adopcionestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcionmodel',
            name='adopcionAnimalEstado',
            field=models.IntegerField(choices=[(1, 'ADOPTADO'), (2, 'NO_ADOPTADO')], db_column='estado_adoptado', default=2),
        ),
    ]
