# Generated by Django 3.2.7 on 2021-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20211018_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcionmodel',
            name='adopcionAnimal',
        ),
        migrations.AddField(
            model_name='productomodel',
            name='productoDisponible',
            field=models.BooleanField(db_column='disponible', default=True),
        ),
    ]
