# Generated by Django 3.2.7 on 2021-10-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20211005_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidomodel',
            old_name='cliente',
            new_name='clientes',
        ),
    ]
