# Generated by Django 3.2.7 on 2021-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_cliente_pedidomodel_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='platoCantidad',
            field=models.IntegerField(db_column='cantidad', default=0),
        ),
    ]
