# Generated by Django 3.2.7 on 2021-10-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_adopcionmodel_adopcionanimalestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopcionmodel',
            old_name='adopcionAnimalEstado',
            new_name='adopcionAnimal',
        ),
        migrations.RemoveField(
            model_name='detallepedidomodel',
            name='metodoPago',
        ),
        migrations.DeleteModel(
            name='MetodoPagoModel',
        ),
    ]
