# Generated by Django 3.2.7 on 2021-10-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_clientemodel_clientedocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionmodel',
            name='adopcionTamanio',
            field=models.TextField(choices=[('PEQUEÑO', 'P'), ('M', 'MEDIANO'), ('G', 'GRANDE')], db_column='tamanio', default='M'),
        ),
    ]
