# Generated by Django 3.2.7 on 2021-10-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_adopcionmodel_adopciontamanio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionmodel',
            name='adopcionTamanio',
            field=models.TextField(choices=[('PEQUEÑO', 'P'), ('MEDIANO', 'M'), ('GRANDE', 'G')], db_column='tamanio', default='MEDIANO'),
        ),
    ]
