# Generated by Django 3.2.7 on 2021-10-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_productomodel_platocantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productomodel',
            old_name='platoCantidad',
            new_name='productoCantidad',
        ),
    ]
