# Generated by Django 3.2.7 on 2021-10-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20211015_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='createdAt',
            field=models.DateField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='updatedAt',
            field=models.DateField(auto_now=True, db_column='updated_at'),
        ),
    ]
