# Generated by Django 3.2.7 on 2021-10-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20211015_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='pedidoFecha',
            field=models.DateField(auto_now_add=True, db_column='fecha'),
        ),
    ]
