# Generated by Django 3.2.7 on 2021-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_creacion_tablas_casifinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionmodel',
            name='adopcionTamaño',
            field=models.TextField(choices=[('P', 'PEQUEÑO'), ('M', 'MEDIANO'), ('G', 'GRANDE')], db_column='tamanio', default='M'),
        ),
    ]
