# Generated by Django 3.2.7 on 2021-09-30 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_adopcionmodel_adopciontamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionmodel',
            name='clientes',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteAdopcion', to='gestion.clientemodel'),
        ),
    ]
