# Generated by Django 3.2.7 on 2021-10-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_adopcionmodel_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionmodel',
            name='adopcionEdad',
            field=models.IntegerField(db_column='edad', null=True),
        ),
    ]
