# Generated by Django 3.2.7 on 2021-10-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_adopcionmodel_adopcionedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcionmodel',
            name='adopcionFoto',
            field=models.ImageField(db_column='foto', null=True, upload_to='adopciones/'),
        ),
    ]
